<?php
$_API = array
	(
	/**
	 * apiDomain
	 * API서버 도메인
	 * 'http://' or 'https://' 부터 시작합니다.
	 */
	'apiDomain' => 'http://api.smileyanji.com/' ,
	/**
	 * accesskeyId
	 * accesskey ID
	 */
	'accesskeyId' => '1576xGoDjgQs0ff8N0s025K37L979QK9' ,
	/**
	 * accesskeySecret
	 * accesskey 비번
	 */	
	'accesskeySecret' => '$2y$10$YcbcyRwXxuUloK9I/TtSrOwJLm0/UH4X1T796RrV9X5g4AUrAUBr6' ,
	/**
	 * storageKey
	 * 스토리지키
	 */
	'storageKey' => array(
                        'storage'=>'jb1wS5Aw5f66cnnUA852ob9ky341W601',
                        'storage2'=>'151365Roqy9s3uc2Bp16Cg57eVU0O9l1',
                        'storage1'=>'zNjpF1kpwP2v5nY71IT8x9M3mA62H490',
                        ),
    /**
    *
    *
    */
    'version'=>'v1',
    )

?>